import './globals.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import Container from './components/styles/Container'
import CartProvider from '@/providers/CartProvider'
import { Toaster } from 'react-hot-toast'

const poppins = Poppins({ subsets: ['latin'], weight:['400', '700'] })

export const metadata: Metadata = {
  title: 'E-shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='body'>
        <Toaster toastOptions={{
          style: {
            background: "rgb(51 65 85)",
            color: "#fff",
          }
        }}/>
        <CartProvider>
        <div className='content-wrapper'>
            <Header />
            <main className='main'>
              <Container>
                {children}
              </Container>
            </main>
          </div>
          <Footer/>
        </CartProvider>
        </div>
      </body>
    </html>
  )
}
